openbmc-subtree: Remove unused workdir
Removing local_repo_dir from the config file uncovered this unused
variable:

Traceback (most recent call last):
  File "./openbmc-subtree", line 545, in <module>
    sys.exit(0 if main() else 1)
  File "./openbmc-subtree", line 541, in main
    args.func(args)
  File "./openbmc-subtree", line 399, in do_update
    list(all_update_info), args)
  File "./openbmc-subtree", line 367, in
get_commit_message_for_squashed_update
    workdir = args.config[subtree]['local_repo_dir']
  File
"/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py",
line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'local_repo_dir'