subtree update: 868407c65d -> 64c979e88e
poky 52a625582e -> 7035b4b21e:
    applied 911d784d9c8... base.bbclass: add dependency on pseudo from do_prepare_recipe_sysroot
    applied b514e1f0bed... sysstat: fix CVE-2019-16167
    applied 123932ceaa8... bluez5: Fix for --enable-btpclient
    applied 65cc5c2455a... opensbi: Bump from 0.4 to 0.5
    applied fdc1ccbb969... u-boot: Bump from 2019.07 to 2019.10
    applied 4bdf118a743... qemuriscv64: Build smode U-Boot
    applied 3bdce139ffc... libsdl2: fix CVE-2019-13616
    applied 80739381b19... sanity: check the format of SDK_VENDOR
    applied b236454b839... uninative: check .done file instead of tarball
    applied c8535ece54f... openssh: fix CVE-2019-16905
    applied 8d619931eec... wic/rawcopy: Support files in sub-directories
    applied 8569cb2758c... file: explicitly disable seccomp
    applied 6f2670dfea8... i2c-tools: Add missing RDEPEND
    applied 7b87877600b... python3: -dev should depend on distutils
    applied 35ddf66e49c... gawk: add PACKAGECONFIG for readline
    applied c25a3336e28... testimage.bbclass: support hardware-controlled targets
    applied 8073884454f... testimage.bbclass: enable ssh agent forwarding
    applied 077c3bbf2f6... oeqa/runtime/df: don't fail on long device names
    applied 34cce61ece6... oeqa/core/decorator: add skipIfFeature
    applied 568fd6ea472... oeqa/runtime/opkg: skip install on read-only-rootfs
    applied ee9d2f4fcfd... oeqa/runtime/systemd: skip unit enable/disable on read-only-rootfs
    applied 8aef8839363... qemu: Fix CVE-2019-12068
    applied 1b3f5bd39e7... systemd.bbclass: enable all services specified in ${SYSTEMD_SERVICE}
    applied c16d1ff13f1... aspell: upgrade from 0.60.7 to 0.60.8
    applied f484aa6090c... python-native: Remove debug.patch
    applied f7f4cfb51fa... tinderclient: Drop obsolete class
    applied 4b467ed084b... python3: alternative name is python3-config not python-config
    applied 52fe6a79d97... python3: ensure that all forms of python3-config are in python3-dev
    applied 586175df3b1... devtool: Add --remove-work option for devtool reset command
    applied 88a4e3cd31e... bison:upgrade 3.4.1 -> 3.4.2
    applied dbba06d9153... cmake.bbclass: add HOSTTOOLS_DIR to CMAKE_FIND_ROOT_PATH
    applied c501f953821... ell: update to 0.23
    applied 3e0c8798af5... devtool: add ssh key option to deploy-target param
    applied d27729ebd0e... e2fsprogs:upgrade 1.45.3 -> 1.45.4
    applied f82f4fae7ef... openssl: make OPENSSL_ENGINES match install path
    applied 7fef74ae95b... ruby: update to v2.6.4
    applied 0130498a8ff... icecc: Export ICECC_CC and friends via wrapper-script
    applied 6f4102f4f63... ruby: some ptest fixes
    applied 9b607c58ffa... oeqa/selftest: use specialist assert* methods
    applied f3d8fea6c7f... bluez5: refresh upstreamed patches
    applied cf775f56b9d... python: Fix CVE-2019-10160
    applied 45a97bccf66... libgcrypt: fix CVE-2019-12904
    applied b49803dfe18... dbus: update dbus-1.init to reflect new PID file
    applied 82ca21d1280... xorgproto: fix summary
    applied a53018699bc... libxvmc:upgrade 1.0.11 -> 1.0.12
    applied 1c2ea784f43... libx11: upgrade to 1.6.9
    applied 1ec8ea34f2d... xorgproto: upgrade to 2019.2
    applied 1cf01c03519... llvm: add missing Upstream-Status tags
    applied 864c8d67f2e... oeqa/selftest/recipetool: Use with to control file handle lifetime
    applied c4f2a115f72... oe.types.path: Use with to control file handle lifetime
    applied 3af1c66939a... lib/oe/packagedata: Use with to control file handle lifetime
    applied f3f15972494... lib/oe/package_manager: Use with to control file handle lifetime
    applied a92ef13e3dc... report-error.bbclass: Use with to control file handle lifetime
    applied 95dca0ec5a8... package.bbclass: Use with to manage file handle lifetimes
    applied 4bc072c7fb4... devtool-source.bbclass: Use with to manage file handle lifetime
    applied e6deec21d6d... libc-package.bbclass: Use with to manage filehandle in do_spit_gconvs
    applied f0f2a492f37... oeqa/runtime/context.py: ignore more files when loading controllers
    applied 73bb8db5292... python3-pip:upgrade 19.2.3 -> 19.3.1
    applied b9703df2853... python-setuptools:upgrade 41.2.0 -> 41.4.0
    applied 82342ab6d4a... util-linux: fix PKNAME name is NULL when use lsblk [LIN1019-2963]
    applied c90c3062ba6... libcap-ng:upgrade 0.7.9 -> 0.7.10
    applied 3d4645df48d... meson: Backport fix to assist meta-oe breakage
    applied ff408c97933... sudo: fix CVE-2019-14287
    applied 6b8c51ae092... adwaita-icon-theme: upgrade 3.32.0 -> 3.34.0
    applied 34d14c25ee8... go: fix CVE-2019-16276
    applied 8ec9acb55da... wic/help: change 'wic write' help description
    applied a94e0e14e1f... wic/engine: use 'linux-swap' for swap file system
    applied 66b6ddf80cc... kernel-fitimage: Cope with non-standard kernel deploy subdirectory
    applied dcf52753abc... kernel-devicetree: Cope with non-standard kernel deploy subdirectory
    applied 64a684611f4... connman: mark connman-wait-online as SYSTEMD_PACKAGE
    applied 269f3c88734... ref-manual: First pass of 2.8 migration changes (WIP)
    applied ca2dc293266... poky.ent: Updated the release date to October 2019
    applied 9db609edf7e... dev-manual: Added info to "Selecting an Initialization Manager"
    applied c1fc3ed4076... ref-manual: 2nd pass 3.0 migration
    applied 3eb09fd7376... documenation: Changed "2.8" to "3.0".
    applied b70a4d8d5d7... ref-manual: Removed deprecated link to ref-classes-bluetooth
    applied 495bb1e329c... ref-manual, dev-manual: Clean up of a commit
    applied 20d648416b4... ref-manual: Updated the BUSYBOX_SPLIT_SUID variable.
    applied ff0db7b88ec... ref-manual, dev-manual: Added CMake toolchain files.
    applied 13bfb2b8695... gsettings-desktop-schemas: upgrade 3.32.0 -> 3.34.0
    applied e7bf9c976cc... meta: update and add missing homepage/bugtracker links
    applied deb2aea4eb8... meta: add missing description in recipes-gnome
    applied 37388b6899b... buildhistory-analysis: filter out -src changes by default
    applied 85903df1c15... bind: fix CVE-2019-6471 and CVE-2018-5743
    applied 6d77529d622... unfs3: fixed the issue that unfsd consumes 100% CPU
    applied 423d32dae2e... python3: fix CVE-2019-16935
    applied 7a7d6ac3eb7... python: fix CVE-2019-16935
    applied 8a1e7bd5dc9... nfs-utils: Improve handling when no exported fileysystems
    applied cedd55fc3e6... squashfs-tools: Upgrade to 4.4
    applied dbf5285f868... screen: Upgrade 4.6.2 -> 4.7.0
    applied a090ee097b5... stress-ng: Upgrade 0.10.00 -> 0.10.08
    applied 38b772dab7b... nspr: Upgrade 4.21 -> 4.23
    applied c79f8c15139... gcc: Remove stale gcc 8 patchfile
    applied 2812d501282... qemu: Avoid potential build configuration contamination
    applied d02c3e4495d... bitbake: bitbake: contrib/vim: initial commit, with unmodified code from indent/python.vim
    applied 4bedd3c4529... bitbake: bitbake: contrib/vim: Modify Python indentation to work with 'python do_task {'
    applied beda62448dc... bitbake: bitbake: prserv/serv: Use with while reading pidfile
    applied 5107dce38e6... bitbake: bitbake: ConfHandler: Use with to manage filehandle lifetime
    applied d52cb2f01ab... bitbake: fetch2/git: fetch shallow revs when needed
    applied 3a751d5564f... bitbake: tests/fetch: add test for fetching shallow revs
    applied 5e040b69c30... gnu-efi: Upgrade 3.0.9 -> 3.0.10
    applied 5c24170fa28... libcap-ng: undefined reference to `pthread_atfork'
    applied f2892ed6aa0... python3-numpy: Stop shipping manual config files
    applied a786c86cf15... squashfs-tools: remove redundant source checksums
    applied 64ab3b9bf1e... squashfs-tools: clean up compile/install tasks
    applied 5688b60523a... wpa-supplicant: fix CVE-2019-16275
    applied 4f3655a642e... ofono: tidy up the recipe
    applied ab808af9fda... binutils: fix CVE-2019-17450
    applied efea2749d28... binutils: fix CVE-2019-17451
    applied f3c32efa9ba... libsdl2: Fix build failure when using mesa 19.2.1
    applied 5c33b6fd8a7... makedevs: fix format strings in makedevs.c in print statements
    applied b12c9e256db... makedevs: fix invalidScanfFormatWidth to prevent overflowing usr_buf
    applied 29b733d7b87... IMAGE_LINGUAS_COMPLEMENTARY: auto-add language packages other than locales
    applied 02951c25c9... systemtap: support usrmerge
    applied 1b97c75552... sudo: Fix fetching sources
    applied 4506cb4e34... kernel-fitimage: introduce FIT_SIGN_ALG
    applied b983342847... ncurses: fix CVE-2019-17594, CVE-2019-17595
    applied 0fe457d6d8... gcr: update to 3.34.0
    applied eda78d090e... gcr: remove intltool-native
    applied 27f1aa36f5... btrfs-tools: update to 5.3
    applied b245171a00... libmodulemd-v1: update to 1.8.16
    applied 1d67123f17... elfutils: add PACKAGECONFIG for compression algorithms
    applied 3a54afa744... elfutils: disable bzip
    applied 6df6e5d3ba... libtiff: fix CVE-2019-17546
    applied 3a1ad58f74... libxslt: fix CVE-2019-18197
    applied f4a337e472... mdadm: fix do_package failed when changed local.conf but not cleaned
    applied 2864d40e0b... ell: update to 0.25
    applied a5de8b48ab... ltp: Fix overcommit_memory failure
    applied 3e36ab8dad... cve-check: ensure all known CVEs are in the report
    applied 116e9519b6... git: some tools are no longer perl, so move to main recipe
    applied 5c5a58d255... git: cleanup man install
    applied b23f006851... coreutils: Move stdbuf into an own package coreutils-stdbuf
    applied a348b3aa77... qemu-helper-native: add missing option to getopt() call
    applied cb8fbf5d92... qemu-helper-native: showing help shouldn't be an error
    applied 56ddcbf25d... qemu-helper-native: pass compiler flags
    applied ce0b46650f... oeqa/selftest: add test for oe-run-native
    applied ae479d86d1... libical: add PACKAGECONFIG glib and enable it by default
    applied 5ef00559e7... linux-yocto/4.19: update to v4.19.78
    applied 28b5077322... linux-yocto/5.2: update to v5.2.20
    applied 2c6f420640... perf: fix v5.4+ builds
    applied f6166e64f1... perf: create directories before copying single files
    applied a2b0925e10... perf: add 'cap' PACKAGECONFIG
    applied 2f9b303ed4... perf: drop 'include' copy
    applied 55d33e6f76... cve-check: failure to parse versions should be more visible
    applied d3f5986a2e... gstreamer1.0: upgrade to version 1.16.1
    applied ad9ab28803... gstreamer1.0-plugins-base: upgrade to version 1.16.1
    applied 91efaedc0f... gstreamer1.0-plugins-good: upgrade to version 1.16.1
    applied 95bc12ccfc... gstreamer1.0-plugins-bad: upgrade to version 1.16.1
    applied 005f4da736... gstreamer1.0-plugins-ugly: upgrade to version 1.16.1
    applied 412525ba41... gstreamer1.0-libav: upgrade to version 1.16.1
    applied 0f51e9a5f5... gstreamer1.0-vaapi: upgrade to version 1.16.1
    applied 321b80ebb3... gstreamer1.0-omx: upgrade to version 1.16.1
    applied a871348eda... gstreamer1.0-python: upgrade to version 1.16.1
    applied 6e44090771... gstreamer1.0-rtsp-server: upgrade to version 1.16.1
    applied 9cc82a6f43... gst-validate: upgrade to version 1.16.1
    applied 421b8d43ab... gstreamer: Change SRC_URI to use HTTPS access instead of HTTP
    applied b8f8707dfe... libgcrypt: upgrade 1.8.4 -> 1.8.5
    applied f954018d8d... gst-examples: rename so PV is in filename
    applied 79018ee8d9... sanity: check for more bits of Python
    applied fca7712bf4... mesa: fix meson configure fix when 'dri' is excluded from PACKAGECONFIG
    applied d1fb08991e... selftest: skip virgl test on centos 7 entirely
    applied feea1ef48d... recipeutils-test: use a small dependency in the dummy recipe
    applied 26071fb155... nfs-utils: do not depend on bash unnecessarily
    applied e40596c4d4... ell: update to 0.26
    applied f03d4a72f0... gnu-efi: Upgrade 3.0.10 -> 3.0.11
    applied 6c7ceeab99... ofono: update to 1.31
    applied 222f6b3319... selftest: add a test for gpl3-free images
    applied 03a790db55... libksba: Fix license specification
    applied 7035b4b21e... scripts/oe-pkgdata-util: Enable list-pkgs to print ordered packages

openbmc-subtree update -c master.conf -t openbmc -sxa --shortlog \
    --subtree poky