subtree update: b2fe863db1 -> 1fd136c3b3
poky 23deb29c1b -> c67f57c09e:
    applied bd7521568f... net-tools: upgrade to latest revision in upstream repo instead of old debian snapshot
    applied 38519b6f4a... ltp: remove --with-power-management-testsuite from EXTRA_OECONF
    applied d88024e783... libdnf: allow reproducible binary builds
    applied 7c3055e70f... stress-ng: create a symlink for /usr/bin/stress
    applied 4eef15704a... buildhistory: use pid for temporary txt file name
    applied b28b7c7c6a... ccache: Upgrade to 3.7.11
    applied 3439ad8616... Revert "python3: define a profile directory path"
    applied 801f07fc00... wic/bootimg-efi: Add support for IMAGE_BOOT_FILES
    applied 93563b5bd4... glibc: Secruity fix for CVE-2020-6096
    applied 6c2bb4a4ad... bitbake: bitbake: command: Handle multiconfig in findSigInfo
    applied 7d82155fd5... rootfs-post: remove traling blanks from tasks
    applied 5008ee45e4... gconf: use python3
    applied c1a56579ff... python3-setuptools: update to 49.2.0
    applied 383b86e921... initscripts: Fix various shellcheck warnings in populate-volatile.sh
    applied 48ba352755... initscripts: Fix populate-volatile.sh bug when file/dir exists
    applied 89fcdf9868... mesa: enable freedreno Vulkan driver if freedreno is enabled
    applied 61a7d0711f... arch-armv8-2a.inc: add tune include for armv8.2a
    applied 32ee392de2... tune-cortexa55.inc: switch to using armv8.2a include file
    applied 02b337e15d... libevdev:upgrade 1.9.0 -> 1.9.1
    applied 9a0ec350ac... mpg123:upgrade 1.26.2 -> 1.26.3
    applied 4cbea10197... checklayer: check layer in BBLAYERS before test
    applied f22e0478fa... perl: Avoid race continually rebuilding miniperl
    applied 32f23b7467... bash-completion: update to 2.11
    applied bbefe04a62... cve-update: handle baseMetricV2 as optional
    applied 68dc5f24a7... python3: update to 3.8.5
    applied 9e5dfa356c... re2c: update to 2.0
    applied 3d418733ff... diffoscope: update to 153
    applied 49e92f8d6d... patch.py: Change to more strictly fuzz detection
    applied 7b78e1b4de... json-c: update to 0.15
    applied 34dc8571d2... package_manager: Move to package_manager/__init__.py
    applied a0416ca06e... rpm: Move manifest to its own subdir
    applied 59397b3a01... ipk: Move ipk manifest to its own subdir
    applied 9129dfe523... deb: Move deb manifest to its own subdir
    applied b8d3d22ccd... rpm: Move rootfs to its own dir
    applied 873aee855f... ipk: Move rootfs to its own dir
    applied 6fd8b17748... deb: Move rootfs to its own dir
    applied e9e2e32999... rpm: Move sdk to its own dir
    applied bfa8f4c098... ipk: Move sdk to its own dir
    applied 635305fe27... deb: Move sdk to its own dir
    applied c5bea36b72... rpm: Move package manager to its own dir
    applied 5bc67f5502... ipk: Move package manager to its own dir
    applied f5f6ae2986... deb: Move package manager to its own dir
    applied f7d7a827b2... layer.conf: fix adwaita-icon-theme signature change problem
    applied bdf966739a... git: update 2.28.0
    applied 1592cdaf83... llvm: upgrade 9.0.1 -> 10.0.1
    applied 94eb5724b1... gcc: Fix mangled patch
    applied 449e07c197... bitbake: server/process: Fix UI first connection tracking
    applied 4cc76db0a0... bitbake: server/process: Account for xmlrpc connections
    applied cacfbbdada... wic/bootimg-efi: Update docs for IMAGE_BOOT_FILES support in bootimg-efi
    applied 9036f84956... gtk-icon-cache.bbclass: add features_check
    applied 0b70525986... cogl-1.0: correct X11 dependencies
    applied 2a401a2959... popt: upgrade to 1.18
    applied 1739fee633... lib/oe/log_colorizer.py: add LogColorizerProxyProgressHandler
    applied d50a04c304... bitbake: build: print traceback if progress handler can't be created
    applied ef0ca299d6... bitbake: build: create_progress_handler: fix calling 'get' on NoneType
    applied 4e3240220b... Revert "lib/oe/log_colorizer.py: add LogColorizerProxyProgressHandler"
    applied 20e9df5721... lib/oe/reproducible.py: Fix git HEAD check
    applied 4c57328478... flex: Refresh patch
    applied 4b6cafae71... pbzip2: extend for nativesdk
    applied 92d9cc304d... nativesdk-rpm: adjust RPM_CONFIGDIR paths dynamically
    applied 29e52bff3c... libwpe: update to 1.7.1
    applied dca94d9aa4... qemumips: Use 34Kf CPU emulation
    applied b70c39767c... lib/package_manager: Fix missing imports
    applied f5f14239cc... ltp: remove OOM tests from runtest/mm
    applied c25bdec524... conf/machine: set UBOOT_MACHINE for qemuarm and qemuarm64
    applied 9647949d22... stress-ng:upgrade 0.11.15 -> 0.11.17
    applied 1790fd9b56... sudo:upgrade 1.9.1 -> 1.9.2
    applied 0c0a03eb4a... sysvinit: update 2.96 -> 2.97
    applied 65525a3c6a... kbd: update 2.2.0 -> 2.3.0
    applied da4b3eecb4... gnu-config: update to latest revision
    applied 3c3ff0fe40... go: update 1.14.4 -> 1.14.6
    applied 61228679ec... meson: update 0.54.3 -> 0.55.0
    applied d9cfecad12... nasm: update 2.14.02 -> 2.15.03
    applied 85d3e045bd... glib-2.0: correct build with latest meson
    applied ce74971998... rsync: update 3.2.1 -> 3.2.2
    applied 5c185dd6f7... vala: update 0.48.6 -> 0.48.7
    applied bf63957752... logrotate: update 3.16.0 -> 3.17.0
    applied 06838f93e5... mesa: update 20.1.2 -> 20.1.4
    applied 499c092ff5... libcap: update 2.36 -> 2.41
    applied 5e1bc3ef5a... net-tools: fix upstream version check
    applied e27d8d20b1... meson.bbclass: add a cups-config entry
    applied 64dff5fd18... linux-yocto/5.4: update to v5.4.53
    applied bb983b8f80... linux-yocto/5.4: fix perf build with binutils 2.35
    applied 2b44ac076c... kernel/yocto: allow dangling KERNEL_FEATURES
    applied 9471602f5a... linux-yocto/5.4: update to v5.4.54
    applied 97bef7627b... libunwind: Backport a fix for -fno-common option to compile
    applied 3488a38e60... dhcp: Use -fcommon compiler option
    applied b148043e0e... kernel-devicetree: Fix intermittent build failures caused by DTB builds
    applied 35d23eaf53... inetutils: Fix build with -fno-common
    applied cac052cdec... libomxil: Use -fcommon compiler option
    applied d9f2e59317... kexec-tools: Fix build with -fno-common
    applied 140483d180... distcc: Fix build with -fno-common
    applied 1beb67e4df... libacpi: Fix build with -fno-common
    applied b6b6a39ee8... ltp: make copyFrom scp command non-fatal
    applied 7ac4833236... allarch: Add missing allarch ttf-bitstream-vera
    applied a5ba89ac4b... musl: Upgrade to latest release 1.2.1
    applied 781e2a8d95... minicom: Fix build when using -fno-common
    applied f39694933a... wic: fix typo
    applied 939690c9e4... systemtap: update to 4.3 latest
    applied dfa3d5e395... kernel-devsrc: fix x86 (32bit) on target module build
    applied 4a832bc5d5... lttng-modules: update to 2.12.2 (fixes v5.8+ builds)
    applied 56b201df77... binutils: Upgrade to 2.35 release
    applied d5bb221646... yocto-bsps: update reference BSPs to 5.4.54
    applied 8f8ec92d7b... kernel-fitimage: build configuration for image tree when dtb is not present
    applied 12521660ec... oeqa/selftest/imagefeatures: Add testcase for fitImage
    applied 4a74697970... xf86-video-intel: Fix build with -fno-common
    applied ddd3e25679... grub: set CVE_PRODUCT to grub2
    applied 6ec51d096e... ghostscript: fix CVE-2020-15900
    applied d3c60cde03... qemu : fix CVE-2020-15863
    applied f87f1a7eec... libcap: Upgrade 2.41 -> 2.42
    applied df8b8c553e... libinput: Upgrade 1.15.6 -> 1.16.0
    applied bf2b4c6943... python3-setuptools: Upgrade 49.2.0 -> 49.2.1
    applied bfabdcfa37... cml1: Add the option to choose the .config root dir
    applied 24f830fc75... kernel-yocto: enhance configuration queue analysis capabilities
    applied db05c02af4... strace: update to 5.8 (fix build against v5.8 uapi headers)
    applied 4901fc6d27... populate_sdk_ext: Ensure buildtools doesn't corrupt OECORE_NATIVE_SYSROOT
    applied 26499d1b08... buildtools: Handle generic environment setup injection
    applied 917032944e... uninative: Handle PREMIRRORS generically
    applied 3ee166c0dd... oeqa: write @OETestTag content into json test reports for each case
    applied 470c58ba45... systemd: Upgrade v245.6 -> v246
    applied 392c117e7a... glibc: Upgrade to 2.32 release
    applied 6f9d4614e9... ref-manual: Add documentation for kernel-fitimage
    applied e4e6756308... bitbake: progress: modernize syntax, format
    applied 9b41300d47... bitbake: progress: fix hypothetical NameError if 'progress' isn't set
    applied 5a80602564... bitbake: progress: filter ANSI escape codes before looking for progress text
    applied 1752a47664... bitbake: tests/color: add test suite for ANSI color code filtering
    applied f664ecb910... bitbake: data: emit filename/lineno information for shell functions
    applied a06e5ac221... libhandy: upstream has moved to gnome
    applied e4f6ea6811... libexif: Enable native and nativesdk
    applied 9e2c0e57df... cmake.bbclass: Rework compiler program variables for allarch
    applied 98549fd68c... runqemu: fix permission check of /dev/vhost-net
    applied dc74b6e8d5... python3: Improve handling of python3 manifest generation
    applied 56fd64447c... python3-manifest.json: Updates
    applied 75a5e8ad05... gcr: make sure gcr-oids.h is generated
    applied 7e658aebed... maintainers: Update entries for Mark Hatle
    applied 883b4377f8... gcr: Fix patch Upstream-Status from v2 patch
    applied 528bdfc860... go: Upgrade to 1.14.7
    applied 65a2323431... gcc: backport a fix for out-of-line atomics on aarch64
    applied e5d9d71b47... binutils: Remove RISC-V PIE patch
    applied 0c91113c07... bitbake: server/process: Remove pointless process forking
    applied a3448ad15e... bitbake: server/process: Simplfy idle callback handler function
    applied b4919c7ad7... bitbake: server/process: Pass timeout/xmlrpc parameters directly to the server
    applied 2976f43c22... bitbake: server/process: Add extra logfile flushing
    applied a00c64d320... python3-setuptools: update to 49.3.1
    applied eccfc1f5a5... linux-yocto-rt/5.4: update to rt32
    applied 70231e3230... linux-yocto/5.4: update to v5.4.56
    applied 2323531c10... linux-yocto/5.4: update to v5.4.57
    applied d23cfcf727... kernel.bbclass: Configuration for environment with HOSTCXX
    applied 17798a89ad... kernel-yocto: set cwd before querying the meta data dir
    applied c74b763e04... kernel-yocto: make # is not set matching more precise
    applied 095175595d... kernel-yocto: split meta data gathering into patch and config phases
    applied b866a973ac... make-mod-scripts: add HOSTCXX definitions and gmp-native dependency
    applied 84daf88c9c... kernel-devsrc: fix on target modules prepare for ARM
    applied fc2b9f7f99... kernel-devsrc: 5.8 + gcc10 require gcc-plugins + libmpc-dev
    applied 8731b9879c... qemu.inc: Use virtual/libgl instead of mesa
    applied bd1da2aca0... perl: Add check for non-arch Storable.pm file
    applied b1cd7723c4... bitbake: build: print a backtrace when a Bash shell function fails
    applied 0e15931688... bitbake: build: print a backtrace with the original metadata locations of Bash shell funcs
    applied f31ed30c11... packagefeed-stability: Remove as obsolete
    applied 1a801e2354... build-compare: Drop recipe
    applied e95851d966... webkitgtk: Upgrade to 2.28.4
    applied 0bdb86b457... gobject-introspection: disable scanner caching in install
    applied 33f3cf3aae... librsvg: Upgrade 2.40.20 -> 2.40.21
    applied de11fb92cf... gcc-runtime.inc: fix m32 compile fail with x86-64 compiler
    applied 1bff01bda9... fribidi: extend CVE_PRODUCT to include fribidi
    applied 7e25a6b4d5... qemu: Upgrade 5.0.0 -> 5.1.0
    applied 2d54561f74... kexec-tools: Fix additional duplicate symbols on aarch64/x86_64 builds
    applied a8fef8bee7... gcc: Upgrade to 10.2.0
    applied 482cee03f2... selftest/tinfoil: Increase wait event timeout
    applied 11651de07d... lttng-tools: upgrade 2.12.1 -> 2.12.2
    applied 7b732da82a... linux-yocto/5.4: update to v5.4.58
    applied 196e8c6daf... linux-yocto/5.4: perf cs-etm: Move definition of 'traceid_list' global variable from header file
    applied a8b4215985... buildcpio.py: Apply patch to fix build with -fno-common
    applied b230ee4eaf... buildgalculator: Patch to fix build with -fno-common
    applied a8558cbf7d... localedef: Update to include floatn.h fix
    applied d41805aa5e... conf/machine: set UBOOT_MACHINE for qemumips and qemumips64
    applied fe80568a88... multilib.conf: add u-boot to NON_MULTILIB_RECIPES
    applied 4d02faf634... libubootenv: uprev to v0.3
    applied 49865a6061... libffi: fix multilib header conflict
    applied 5349866935... alsa-topology-conf: use ${datadir} in do_install()
    applied b5a1389b47... alsa-ucm-conf: use ${datadir} in do_install()
    applied 84bc48263f... harfbuzz: upgrade 2.6.8 -> 2.7.1
    applied 073ef419d5... sqlite3: upgrade 3.32.3 -> 3.33.0
    applied 255c900701... stress-ng: upgrade 0.11.17 -> 0.11.18
    applied 3e57921973... x264: upgrade to latest revision
    applied 9e82d25fd3... xserver-xorg: Fix build with -fno-common/mips
    applied 21c13f75b5... runqemu: Check gtk or sdl option is passed together with gl or gl-es options.
    applied 8db6cf92b4... oeqa/manual/bsp-hw.json : remove shutdown_system test
    applied 660f5694dd... oeqa/manual/bsp-hw.json : remove X_server_can_start_up_with_runlevel_5_boot test
    applied 56e6931c50... iproute2: upgrade 5.7.0 -> 5.8.0
    applied b75ae656fa... ethtool: upgrade 5.7 -> 5.8
    applied 85869d615b... package.bbclass: Sort shlib2 output for hash equivalency
    applied 76dbaaf5e2... weston: add missing packageconfigs
    applied 58eb470cad... gpgme: fix multilib header conflict
    applied c36fb625d1... perf: backport a fix for confusing non-fatal error
    applied 57d5f4ad41... libc-headers: update to v5.8
    applied b8036e017c... linux-yocto: introduce 5.8 reference kernel
    applied 4ccc353330... kernel-yocto/5.8: add gmp-native dependency
    applied 3558af1ce6... linux-yocto/5.8: update to v5.8.1
    applied 5731777f62... cortex-m0plus.inc: Add tuning for cortex M0 plus
    applied f809d27e29... binutils: Let crosssdk gold linker generate 4096 btyes long .interp section
    applied 52635969f9... gcc-cross-canadian: Correct the regexp to delete versioned gcc binary
    applied 828298c4bb... systemd: Move musl patches to SRC_URI_MUSL
    applied be65fe73b7... systemd: Fix path to modules-load.d et al
    applied c73b843f91... nfs-utils: Drop StandardError=syslog from systemd unit
    applied c52cb6a8b8... openssh: Drop StandardError=syslog from systemd unit
    applied e5ff035e85... volatile-binds: Drop StandardOutput=syslog from systemd unit
    applied 7c25854ee6... systemd: Upgrade v246 -> v246.1
    applied 4d37676006... systemd: Upgrade v246.1 -> v246.2
    applied d416bb3a68... curl: Upgrade to 7.72.0
    applied c67f57c09e... bitbake: build: make shell traps less chatty when 'bitbake -v' is used

openbmc-subtree update -c master.conf -t openbmc -sxa --shortlog \
    --subtree poky